from django.conf.urls import patterns, url

urlpatterns = patterns('blg.views',
                        url('^$','home'),
                        url(r'^article/(\d+)/$', 'getarticle', name='article'),
                        url(r'^edit/(\d+)/$','editarticle'),
                        url(r'^upload_json/$','uploadjson'),
                        url(r'^new/$','newarticle'),
                        url(r'^login/$','Login'),
                        url(r'^logout/$','Logout'),
                        url(r'^addcat/$','addcat'),
                        url(r'^list/$','listcat'),
                        url(r'^about/$','getarticle'),
                        url(r'^comment/(\d+)/$', 'makecomment', name='makecomment'),
                        url(r'^comment_photo/(\d+)/$', 'comment_photo'),
                        url(r'^(\d{4})/(\d{1,2})/$', 'listdate'),
                        url(r'^(\d{4})/(\d{1,2})/(\d{1,2})/$', 'listdate'),
                        url(r'^photo/$', 'photo'), 
                        url(r'^search/$', 'search'), 
                        url(r'^create_album/$', 'create_album'), 
                        url(r'^photo_list/$', 'photo_list'), 
                        url(r'^uploadfile/$', 'uploadfile'), 
                        url(r'^det_photo/$', 'det_photo'), 
                      )
